<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>it.unifi.balpha.store</groupId>
  <artifactId>inventory-management-app</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>inventory-management-app</name>
	<profiles>
	    <profile>
	        <id>docker-env</id>
	        <properties>
	            <env.TESTCONTAINERS_RYUK_DISABLED>true</env.TESTCONTAINERS_RYUK_DISABLED>
	        </properties>
	    </profile>
	    <profile>
	        <id>mutation-testing</id>
	        <build>
	            <plugins>
					<plugin>
					    <groupId>org.pitest</groupId>
					    <artifactId>pitest-maven</artifactId>
					    <version>1.15.3</version>
					    <configuration>
					        <targetClasses>
					            <param>it.unifi.balpha.store.Category</param>
					            <param>it.unifi.balpha.store.Product</param>
					            <param>it.unifi.balpha.store.InventoryService</param>
					            <param>it.unifi.balpha.store.InventoryPresenterImpl</param>
					            <param>it.unifi.balpha.store.*JpaRepository</param>
					        </targetClasses>
					        
					        <targetTests>
							    <param>it.unifi.balpha.store.InventoryPresenterTest</param>
							    <param>it.unifi.balpha.store.CategoryJpaRepositoryTest</param>
							    <param>it.unifi.balpha.store.CategoryTest</param>
							    <param>it.unifi.balpha.store.ProductTest</param>
							    <param>it.unifi.balpha.store.InventoryServiceTest</param>
							</targetTests>
					        
					        <jvmArgs>
					            <jvmArg>-Djava.awt.headless=true</jvmArg>
					        </jvmArgs>
					    </configuration>
					    <dependencies>
					        <dependency>
					            <groupId>org.pitest</groupId>
					            <artifactId>pitest-junit5-plugin</artifactId>
					            <version>1.2.1</version>
					        </dependency>
					    </dependencies>
					</plugin>
	            </plugins>
	        </build>
	    </profile>
	</profiles>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>11</maven.compiler.release>
    <junit.version>5.10.2</junit.version>
  </properties>

  <dependencies>
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <version>${junit.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-engine</artifactId>
        <version>${junit.version}</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>jakarta.persistence</groupId>
        <artifactId>jakarta.persistence-api</artifactId>
        <version>3.1.0</version>
    </dependency>
    <dependency>
        <groupId>org.hibernate.orm</groupId>
        <artifactId>hibernate-core</artifactId>
        <version>6.4.4.Final</version>
    </dependency>
    <dependency>
        <groupId>com.h2database</groupId>
        <artifactId>h2</artifactId>
        <version>2.2.224</version>
    </dependency>

    <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-junit-jupiter</artifactId>
        <version>5.11.0</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>org.assertj</groupId>
        <artifactId>assertj-swing-junit</artifactId>
        <version>3.17.1</version>
        <scope>test</scope>
    </dependency>
    
    <dependency>
	    <groupId>org.postgresql</groupId>
	    <artifactId>postgresql</artifactId>
	    <version>42.7.3</version>
	</dependency>
	<dependency>
	    <groupId>org.testcontainers</groupId>
	    <artifactId>testcontainers</artifactId>
	    <version>1.19.3</version>
	    <scope>test</scope>
	</dependency>
	<dependency>
	    <groupId>org.testcontainers</groupId>
	    <artifactId>junit-jupiter</artifactId>
	    <version>1.19.3</version>
	    <scope>test</scope>
	</dependency>
	<dependency>
	    <groupId>org.testcontainers</groupId>
	    <artifactId>postgresql</artifactId>
	    <version>1.19.3</version>
	    <scope>test</scope>
	</dependency>
	
  </dependencies>

  <build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.11.0</version>
        </plugin>
        
        <plugin>
		    <groupId>org.apache.maven.plugins</groupId>
		    <artifactId>maven-surefire-plugin</artifactId>
		    <version>3.2.2</version>
		    <configuration>
		        <environmentVariables>
		            <DOCKER_HOST>unix:///var/run/docker.sock</DOCKER_HOST>
		            <TESTCONTAINERS_RYUK_DISABLED>true</TESTCONTAINERS_RYUK_DISABLED>
		        </environmentVariables>
		    </configuration>
		</plugin>

        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>3.2.5</version>
            <configuration>
		        <environmentVariables>
		            <DOCKER_HOST>unix:///var/run/docker.sock</DOCKER_HOST>
		            <TESTCONTAINERS_RYUK_DISABLED>true</TESTCONTAINERS_RYUK_DISABLED>
		        </environmentVariables>
		    </configuration>
            <executions>
                <execution>
                    <id>integration-tests</id>
                    <phase>integration-test</phase>
                    <goals>
                        <goal>integration-test</goal>
                    </goals>
                </execution>
                <execution>
                    <id>verify</id>
                    <phase>verify</phase>
                    <goals>
                        <goal>verify</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        
        <plugin>
		    <groupId>org.codehaus.mojo</groupId>
		    <artifactId>exec-maven-plugin</artifactId>
		    <version>3.6.3</version>
		    <configuration>
		        <mainClass>it.unifi.balpha.store.Main</mainClass>
		    </configuration>
		</plugin>
		<plugin>
		    <groupId>org.jacoco</groupId>
		    <artifactId>jacoco-maven-plugin</artifactId>
		    <version>0.8.11</version>
		    <executions>
		        <execution>
		            <goals>
		                <goal>prepare-agent</goal>
		            </goals>
		        </execution>
		        <execution>
		            <id>report</id>
		            <phase>verify</phase>
		            <goals>
		                <goal>report</goal>
		            </goals>
		        </execution>
		    </executions>
		</plugin>
    </plugins>
  </build>
</project>